Allow adding empty `filename` param to `content-disposition`
postmanlabs/form-data pull request #2
Opened 2020-01-03 08:55 UTC by coditva

Allows adding `filename` as an empty string in `content-disposition`.

2020-01-07 10:29 UTC, vikiCoder requested changes

2020-01-07 10:29 UTC, vikiCoder commented on lib/form_data.js
> +  } else if (value.name || value.path) {
undefined value could cause problem here 🤔

2020-01-08 07:43 UTC, vikiCoder approved these changes

2020-01-09 04:45 UTC, codenirvana approved these changes

2020-01-09 05:47 UTC, merged