Unnecessary quotes around encoded filename* parameter
postmanlabs/form-data pull request #3
Opened 2020-09-18 02:50 UTC by lucifercr07

Issue: Unnecessary quotes were added around encoded `filename*` parameter, according to the relevant RFCs
(https://tools.ietf.org/html/rfc6266 & https://tools.ietf.org/html/rfc5987),
filename*= does not support quoted-string values only percent-encoding.

Updating the code to not add quotes around `filename*` param.

2020-09-18 04:57 UTC, coditva requested changes

2020-09-18 04:57 UTC, coditva commented on lib/form_data.js
> +    contentDisposition.push('filename*=' + this._encodeHeaderParam(filename) + '');
```suggestion
    contentDisposition.push('filename*=' + this._encodeHeaderParam(filename));
```

2020-09-18 05:58 UTC, lucifercr07 commented on lib/form_data.js
> +    contentDisposition.push('filename*=' + this._encodeHeaderParam(filename) + '');
Done

2020-09-18 07:07 UTC, coditva commented
@lucifercr07 Let's use descriptive commit messages instead of opaque ones like "Update <filename>", please?

Since this repo doesn't have a changelog file, the history is the only changelog and commit messages like these make it harder to figure out what changed.

You can use this article as reference: https://chris.beams.io/posts/git-commit

2020-09-18 07:18 UTC, coditva approved these changes
LGTM, except commit messages. We can either fix them or squash merge the PR.

2020-09-18 08:09 UTC, lucifercr07 commented
> @lucifercr07 Let's use descriptive commit messages instead of opaque ones like "Update < filename >", please?
> 
> Since this repo doesn't have a changelog file, the history is the only changelog and commit messages like these make it harder to figure out what changed.
> 
> You can use this article as reference: https://chris.beams.io/posts/git-commit

This commit message should ideally be squashed as the first commit message that includes the issue and fix description is generally used as final commit message.

2020-09-21 04:22 UTC, mohitranka commented
@lucifercr07 are you going to squash the PR? As @coditva mentioned, please use good commit messages, that focus on "whys" and "hows", and not just the "whats".

2020-09-23 02:25 UTC, codenirvana approved these changes

2020-09-23 02:25 UTC, merged